<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId> com.vsiwest</groupId>
        <artifactId>moneyfan</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>bikeshed</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Inherited from parent's dependencyManagement -->
        <dependency>
            <groupId>com.vsiwest</groupId>
            <artifactId>bbcursive</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>
</project>