# Default log level
org.slf4j.simpleLogger.defaultLogLevel=info

# Log level for application packages
org.slf4j.simpleLogger.log.com.vsiwest.moneyfan=debug

# Date/time format
# E.g., 2023-10-27 10:30:00:123 +0000
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS Z

# Show thread names
org.slf4j.simpleLogger.showThreadName=true

# Show log name (logger name)
org.slf4j.simpleLogger.showLogName=true

# Show short log name (false to show full log name)
org.slf4j.simpleLogger.showShortLogName=false
