package com.moneyfan.data;

import java.math.BigDecimal;

/**
 * Represents a trading order.
 */
public record Order(
    String symbol,          // e.g., "BTCUSDT"
    OrderSide side,         // BUY or SELL
    OrderType type,         // LIMIT, MARKET, etc.
    BigDecimal quantity,    // Amount of base asset to buy/sell
    BigDecimal price,       // Price for LIMIT orders (can be null for MARKET orders)
    long timestamp,         // Order creation timestamp
    String agentId,         // ID of the agent placing the order
    String orderId          // Unique ID for this order (can be generated by simulator)
) {
    // Convenience constructor for market orders where price might not be initially set by agent
    public Order(String symbol, OrderSide side, OrderType type, BigDecimal quantity, long timestamp, String agentId, String orderId) {
        this(symbol, side, type, quantity, null, timestamp, agentId, orderId);
    }
}
