#!/usr/bin/env python3
"""
MP-Superproject CSV to Parquet Bridge
=====================================

Imports compiled `final-TC-CC-TUNIT.csv` files generated by `fetchklines.sh` 
straight into the Lazy Pandas Parquet datastore. 

Usage:
    python hrm/data/import_mpdata.py --source ~/mpdata/import/klines --dest hrm/data/parquet
"""

import os
import glob
import argparse
import pandas as pd
from pathlib import Path

def convert_mpdata_to_parquet(source_dir: str, dest_dir: str):
    import_path = os.path.expanduser(source_dir)
    out_path = Path(dest_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    # Looking for files like: ~/mpdata/import/klines/1m/BTC/USDT/final-BTC-USDT-1m.csv
    # Also handle variations
    search_pattern = os.path.join(import_path, "**", "final-*.csv")
    csv_files = glob.glob(search_pattern, recursive=True)
    
    if not csv_files:
        print(f"No files matching 'final-*.csv' found in {import_path}")
        return
        
    print(f"Found {len(csv_files)} exported CSV files in {import_path}")
    
    for file in csv_files:
        filename = os.path.basename(file)
        # Parse final-TC-CC-TUNIT.csv
        parts = filename.replace("final-", "").replace(".csv", "").split("-")
        if len(parts) >= 3:
            tc, cc, tunit = parts[0], parts[1], parts[2]
            symbol = f"{tc}{cc}"
            
            # The trainer expects a specific slug format
            slug = symbol.replace("-", "_").replace("/", "_")
            parquet_file = out_path / f"{slug}_{tunit}.parquet"
            # If default 5m logic applies, we might just name it slug.parquet or slug_5m.parquet
            # We'll use just slug.parquet to mirror sync.py's format, unless the codebase demands timeframe extensions
            if tunit in ['5m', '1m', '15m', '1h']:
                 # Let's save it directly to the symbol for unity with the trainer
                 parquet_target = out_path / f"{slug}.parquet"
            else:
                 parquet_target = parquet_file
            
            print(f"Converting {filename} -> {parquet_target}...")
            
            try:
                # The shell script uses these columns outputting to CSV
                # Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,Ignore
                df = pd.read_csv(file)
                
                # Standardize column names to match moneyfan's internal format
                col_map = {
                    'Open_time': 'timestamp',
                    'Open': 'open',
                    'High': 'high',
                    'Low': 'low',
                    'Close': 'close',
                    'Volume': 'volume',
                    'Number_of_trades': 'trades',
                    'Quote_asset_volume': 'quote_volume',
                    'Taker_buy_base_asset_volume': 'taker_buy_base',
                    'Taker_buy_quote_asset_volume': 'taker_buy_quote'
                }
                
                # Rename columns present
                df = df.rename(columns={k: v for k, v in col_map.items() if k in df.columns})
                
                # Setup Time Index for Lazy Evaluation
                if 'timestamp' in df.columns:
                    # Binance stores timestamp in ms
                    df['time'] = pd.to_datetime(df['timestamp'], unit='ms')
                    df = df.set_index('time')
                
                # Upsert into Parquet 
                if parquet_target.exists():
                    existing_df = pd.read_parquet(parquet_target)
                    merged = pd.concat([existing_df, df])
                    merged = merged[~merged.index.duplicated(keep='last')].sort_index()
                    merged.to_parquet(parquet_target, engine='pyarrow')
                    print(f"  Upserted to {parquet_target}. Total rows: {len(merged)}")
                else:
                    df.to_parquet(parquet_target, engine='pyarrow')
                    print(f"  Created {parquet_target} with {len(df)} rows.")
                    
            except Exception as e:
                print(f"  Error processing {file}: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MP-Superproject CSV to Parquet Bridge")
    parser.add_argument("--source", default="~/mpdata/import/klines", help="Directory containing final-*.csv files")
    parser.add_argument("--dest", default="hrm/data/parquet", help="Moneyfan Parquet destination directory")
    args = parser.parse_args()
    
    convert_mpdata_to_parquet(args.source, args.dest)
    print("\nBridge transfer complete!")
